Package:
    build_env: python

Distributions:
    - name: ubuntu
      release: 14.04

      build_deps:
      - libzmq3-dev
      
      deps:
      - libzmq3

      build_cmd:
      - mkdir -p ./build/ss-gen/opt/ss-gen
      - cp ss-gen.py ./build/ss-gen/opt/ss-gen/
      - cp startup-script.template ./build/ss-gen/opt/ss-gen/

      post_install:
      - chmod -R 0775 /opt/ss-gen
