Package:
    build_env: python

Distributions:
    - name: ubuntu
      release: 14.04

      build_deps:
      - python-dev
      - python-setuptools
      
      deps:
      - python

      build_cmd:
      - mkdir -p ./build/ss-gen/opt/ss-gen
      - cp ss-gen.py ./build/ss-gen/opt/ss-gen/
      - cp startup-script.template ./build/ss-gen/opt/ss-gen/

      post_install:
      - chmod -R 0775 /opt/ss-gen

Notifications:
    irc:
    - chat.freenode.net#ipkg-io

    email:
    - euforia@gmail.com
